//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeEvaluationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerInstance
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public int ResponseNum { get; set; }
        public int SurveyInstanceId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual SurveyInstance SurveyInstance { get; set; }
    }
}
