//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeEvaluationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CohortPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CohortPermission()
        {
            this.CohortUsers = new HashSet<CohortUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Cohort { get; set; }
        public int User { get; set; }
        public int Survey { get; set; }
        public int Report { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Permission Permission1 { get; set; }
        public virtual Permission Permission2 { get; set; }
        public virtual Permission Permission3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CohortUser> CohortUsers { get; set; }
    }
}
