//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeEvaluationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveysAvailableTo
    {
        public int ID { get; set; }
        public int SurveyAvailableID { get; set; }
        public int UserSurveyRoleId { get; set; }
        public int Quantity { get; set; }
    
        public virtual UserSurveyRole UserSurveyRole { get; set; }
        public virtual SurveysAvailable SurveysAvailable { get; set; }
    }
}
